/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

import (
	"time"
)

type Webhook struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Boolean to indicate if the webhook is active
	Active bool `json:"active,omitempty"`
	// A title for the webhook for easy recognition.
	Title string `json:"title"`
	// A 24-character secret for the webhook. It's generated by Firefly III when saving a new webhook. If you submit a new secret through the PUT endpoint it will generate a new secret for the selected webhook, a new secret bearing no relation to whatever you just submitted.
	Secret   string           `json:"secret,omitempty"`
	Trigger  *WebhookTrigger  `json:"trigger"`
	Response *WebhookResponse `json:"response"`
	Delivery *WebhookDelivery `json:"delivery"`
	// The URL of the webhook. Has to start with `https`.
	Url string `json:"url"`
}
