/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

type AutocompleteAccount struct {
	Id string `json:"id"`
	// Name of the account found by an auto-complete search.
	Name string `json:"name"`
	// Asset accounts and liabilities have a second field with the given date's account balance.
	NameWithBalance string `json:"name_with_balance"`
	// Account type of the account found by the auto-complete search.
	Type_ string `json:"type"`
	// ID for the currency used by this account.
	CurrencyId string `json:"currency_id"`
	// Currency name for the currency used by this account.
	CurrencyName string `json:"currency_name"`
	// Currency code for the currency used by this account.
	CurrencyCode string `json:"currency_code"`
	// Currency symbol for the currency used by this account.
	CurrencySymbol string `json:"currency_symbol"`
	// Number of decimal places for the currency used by this account.
	CurrencyDecimalPlaces int32 `json:"currency_decimal_places"`
}
