/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

// WebhookTrigger : The trigger for the webhook.
type WebhookTrigger string

// List of WebhookTrigger
const (
	STORE_TRANSACTION_WebhookTrigger   WebhookTrigger = "STORE_TRANSACTION"
	UPDATE_TRANSACTION_WebhookTrigger  WebhookTrigger = "UPDATE_TRANSACTION"
	DESTROY_TRANSACTION_WebhookTrigger WebhookTrigger = "DESTROY_TRANSACTION"
)
