/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

type BudgetLimitStore struct {
	// Use either currency_id or currency_code. Defaults to the user's default currency.
	CurrencyId string `json:"currency_id,omitempty"`
	// Use either currency_id or currency_code. Defaults to the user's default currency.
	CurrencyCode string `json:"currency_code,omitempty"`
	// The budget ID of the associated budget.
	BudgetId string `json:"budget_id"`
	// Start date of the budget limit.
	Start string `json:"start"`
	// Period of the budget limit. Only used when auto-generated by auto-budget.
	Period string `json:"period,omitempty"`
	// End date of the budget limit.
	End    string `json:"end"`
	Amount string `json:"amount"`
}
