/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

// RuleTriggerKeyword : The type of thing this trigger responds to. A limited set is possible
type RuleTriggerKeyword string

// List of RuleTriggerKeyword
const (
	FROM_ACCOUNT_STARTS_RuleTriggerKeyword    RuleTriggerKeyword = "from_account_starts"
	FROM_ACCOUNT_ENDS_RuleTriggerKeyword      RuleTriggerKeyword = "from_account_ends"
	FROM_ACCOUNT_IS_RuleTriggerKeyword        RuleTriggerKeyword = "from_account_is"
	FROM_ACCOUNT_CONTAINS_RuleTriggerKeyword  RuleTriggerKeyword = "from_account_contains"
	TO_ACCOUNT_STARTS_RuleTriggerKeyword      RuleTriggerKeyword = "to_account_starts"
	TO_ACCOUNT_ENDS_RuleTriggerKeyword        RuleTriggerKeyword = "to_account_ends"
	TO_ACCOUNT_IS_RuleTriggerKeyword          RuleTriggerKeyword = "to_account_is"
	TO_ACCOUNT_CONTAINS_RuleTriggerKeyword    RuleTriggerKeyword = "to_account_contains"
	AMOUNT_LESS_RuleTriggerKeyword            RuleTriggerKeyword = "amount_less"
	AMOUNT_EXACTLY_RuleTriggerKeyword         RuleTriggerKeyword = "amount_exactly"
	AMOUNT_MORE_RuleTriggerKeyword            RuleTriggerKeyword = "amount_more"
	DESCRIPTION_STARTS_RuleTriggerKeyword     RuleTriggerKeyword = "description_starts"
	DESCRIPTION_ENDS_RuleTriggerKeyword       RuleTriggerKeyword = "description_ends"
	DESCRIPTION_CONTAINS_RuleTriggerKeyword   RuleTriggerKeyword = "description_contains"
	DESCRIPTION_IS_RuleTriggerKeyword         RuleTriggerKeyword = "description_is"
	TRANSACTION_TYPE_RuleTriggerKeyword       RuleTriggerKeyword = "transaction_type"
	CATEGORY_IS_RuleTriggerKeyword            RuleTriggerKeyword = "category_is"
	BUDGET_IS_RuleTriggerKeyword              RuleTriggerKeyword = "budget_is"
	TAG_IS_RuleTriggerKeyword                 RuleTriggerKeyword = "tag_is"
	CURRENCY_IS_RuleTriggerKeyword            RuleTriggerKeyword = "currency_is"
	HAS_ATTACHMENTS_RuleTriggerKeyword        RuleTriggerKeyword = "has_attachments"
	HAS_NO_CATEGORY_RuleTriggerKeyword        RuleTriggerKeyword = "has_no_category"
	HAS_ANY_CATEGORY_RuleTriggerKeyword       RuleTriggerKeyword = "has_any_category"
	HAS_NO_BUDGET_RuleTriggerKeyword          RuleTriggerKeyword = "has_no_budget"
	HAS_ANY_BUDGET_RuleTriggerKeyword         RuleTriggerKeyword = "has_any_budget"
	HAS_NO_TAG_RuleTriggerKeyword             RuleTriggerKeyword = "has_no_tag"
	HAS_ANY_TAG_RuleTriggerKeyword            RuleTriggerKeyword = "has_any_tag"
	NOTES_CONTAINS_RuleTriggerKeyword         RuleTriggerKeyword = "notes_contains"
	NOTES_START_RuleTriggerKeyword            RuleTriggerKeyword = "notes_start"
	NOTES_END_RuleTriggerKeyword              RuleTriggerKeyword = "notes_end"
	NOTES_ARE_RuleTriggerKeyword              RuleTriggerKeyword = "notes_are"
	NO_NOTES_RuleTriggerKeyword               RuleTriggerKeyword = "no_notes"
	ANY_NOTES_RuleTriggerKeyword              RuleTriggerKeyword = "any_notes"
	SOURCE_ACCOUNT_IS_RuleTriggerKeyword      RuleTriggerKeyword = "source_account_is"
	DESTINATION_ACCOUNT_IS_RuleTriggerKeyword RuleTriggerKeyword = "destination_account_is"
	SOURCE_ACCOUNT_STARTS_RuleTriggerKeyword  RuleTriggerKeyword = "source_account_starts"
)
