/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

import (
	"time"
)

type AvailableBudget struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Use either currency_id or currency_code.
	CurrencyId string `json:"currency_id,omitempty"`
	// Use either currency_id or currency_code.
	CurrencyCode          string `json:"currency_code,omitempty"`
	CurrencySymbol        string `json:"currency_symbol,omitempty"`
	CurrencyDecimalPlaces int32  `json:"currency_decimal_places,omitempty"`
	Amount                string `json:"amount"`
	// Start date of the available budget.
	Start time.Time `json:"start"`
	// End date of the available budget.
	End                time.Time     `json:"end"`
	SpentInBudgets     []BudgetSpent `json:"spent_in_budgets,omitempty"`
	SpentOutsideBudget []BudgetSpent `json:"spent_outside_budget,omitempty"`
}
