/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

import (
	"time"
)

type Attachment struct {
	CreatedAt      time.Time       `json:"created_at,omitempty"`
	UpdatedAt      time.Time       `json:"updated_at,omitempty"`
	AttachableType *AttachableType `json:"attachable_type"`
	// ID of the model this attachment is linked to.
	AttachableId string `json:"attachable_id"`
	// MD5 hash of the file for basic duplicate detection.
	Md5         string `json:"md5,omitempty"`
	Filename    string `json:"filename"`
	DownloadUrl string `json:"download_url,omitempty"`
	UploadUrl   string `json:"upload_url,omitempty"`
	Title       string `json:"title,omitempty"`
	Notes       string `json:"notes,omitempty"`
	Mime        string `json:"mime,omitempty"`
	Size        int32  `json:"size,omitempty"`
}
