/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

type AccountTypeFilter string

// List of AccountTypeFilter
const (
	ALL_AccountTypeFilter                     AccountTypeFilter = "all"
	ASSET_AccountTypeFilter                   AccountTypeFilter = "asset"
	CASH_AccountTypeFilter                    AccountTypeFilter = "cash"
	EXPENSE_AccountTypeFilter                 AccountTypeFilter = "expense"
	REVENUE_AccountTypeFilter                 AccountTypeFilter = "revenue"
	SPECIAL_AccountTypeFilter                 AccountTypeFilter = "special"
	HIDDEN_AccountTypeFilter                  AccountTypeFilter = "hidden"
	LIABILITY_AccountTypeFilter               AccountTypeFilter = "liability"
	LIABILITIES_AccountTypeFilter             AccountTypeFilter = "liabilities"
	DEFAULT_ACCOUNT_AccountTypeFilter         AccountTypeFilter = "Default account"
	CASH_ACCOUNT_AccountTypeFilter            AccountTypeFilter = "Cash account"
	ASSET_ACCOUNT_AccountTypeFilter           AccountTypeFilter = "Asset account"
	EXPENSE_ACCOUNT_AccountTypeFilter         AccountTypeFilter = "Expense account"
	REVENUE_ACCOUNT_AccountTypeFilter         AccountTypeFilter = "Revenue account"
	INITIAL_BALANCE_ACCOUNT_AccountTypeFilter AccountTypeFilter = "Initial balance account"
	BENEFICIARY_ACCOUNT_AccountTypeFilter     AccountTypeFilter = "Beneficiary account"
	IMPORT_ACCOUNT_AccountTypeFilter          AccountTypeFilter = "Import account"
	RECONCILIATION_ACCOUNT_AccountTypeFilter  AccountTypeFilter = "Reconciliation account"
	LOAN_AccountTypeFilter                    AccountTypeFilter = "Loan"
	DEBT_AccountTypeFilter                    AccountTypeFilter = "Debt"
	MORTGAGE_AccountTypeFilter                AccountTypeFilter = "Mortgage"
)
