/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

type RecurrenceUpdate struct {
	Title string `json:"title,omitempty"`
	// Not to be confused with the description of the actual transaction(s) being created.
	Description string `json:"description,omitempty"`
	// First time the recurring transaction will fire.
	FirstDate string `json:"first_date,omitempty"`
	// Date until the recurring transaction can fire. After that date, it's basically inactive. Use either this field or repetitions.
	RepeatUntil string `json:"repeat_until,omitempty"`
	// Max number of created transactions. Use either this field or repeat_until.
	NrOfRepetitions int32 `json:"nr_of_repetitions,omitempty"`
	// Whether or not to fire the rules after the creation of a transaction.
	ApplyRules bool `json:"apply_rules,omitempty"`
	// If the recurrence is even active.
	Active       bool                          `json:"active,omitempty"`
	Notes        string                        `json:"notes,omitempty"`
	Repetitions  []RecurrenceRepetitionUpdate  `json:"repetitions,omitempty"`
	Transactions []RecurrenceTransactionUpdate `json:"transactions,omitempty"`
}
