/*
 * Firefly III API v2.0.12
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-03-16T05:34:43+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that.
 *
 * API version: 2.0.12
 * Contact: james@firefly-iii.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package firefly3

// AccountRoleProperty : Is only mandatory when the type is asset.
type AccountRoleProperty string

// List of AccountRoleProperty
const (
	DEFAULT_ASSET_AccountRoleProperty     AccountRoleProperty = "defaultAsset"
	SHARED_ASSET_AccountRoleProperty      AccountRoleProperty = "sharedAsset"
	SAVING_ASSET_AccountRoleProperty      AccountRoleProperty = "savingAsset"
	CC_ASSET_AccountRoleProperty          AccountRoleProperty = "ccAsset"
	CASH_WALLET_ASSET_AccountRoleProperty AccountRoleProperty = "cashWalletAsset"
	NULL_AccountRoleProperty              AccountRoleProperty = ""
)
